test ws

diff --git a/.github/workflows/Deploy.yaml b/.github/workflows/Deploy.yaml
--- a/.github/workflows/Deploy.yaml
+++ b/.github/workflows/Deploy.yaml
@@ -89,7 +89,7 @@ jobs:
         run: terraform init -backend-config="access_key=${aws_access_key}" -backend-config="secret_key=${aws_secret_key}"
 
       - name: Create workspace
-        run: terraform workspace new "airflow-$environment"
+        run: terraform workspace new "$environment" || echo "Workspace airflow-$environment already exists or cannot be created"
 
       - name: Terraform Validate
         id: validate
